import "@/app/globals.scss"

export const metadata = {
  title: "EditorPage",
  description: "Generated by create next app",
}

export default function EditorLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
