import { ContextProvider } from '@/context/contextProvider'
import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function EditorLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider data={{editor: true}}>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
